environment:
  name: prod
server:
  port:
    8080
spring:
  datasource:
    url: jdbc:postgresql://192.168.100.11:5432/sleepy_ringtail
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
