INSERT INTO categories (name, description) VALUES ('N/A', 'N/A')
INSERT INTO categories (name, description) VALUES ('Bebidas', null)
INSERT INTO categories (name, description) VALUES ('Helados', null)
INSERT INTO categories (name, description) VALUES ('Lácteos', null)
INSERT INTO categories (name, description) VALUES ('Panes', null)
INSERT INTO categories (name, description) VALUES ('Dulces', null)
INSERT INTO categories (name, description) VALUES ('Botanas', null)
INSERT INTO categories (name, description) VALUES ('Vinos', null)

INSERT INTO subcategories (name, description, category_id) VALUES ('Refresco', null, 2)
INSERT INTO subcategories (name, description, category_id) VALUES ('Papas fritas', null, 7)
INSERT INTO subcategories (name, description, category_id) VALUES ('Chocolate', null, 6)
INSERT INTO subcategories (name, description, category_id) VALUES ('Chicles', null, 6)
INSERT INTO subcategories (name, description, category_id) VALUES ('Helado base agua', null, 3)
INSERT INTO subcategories (name, description, category_id) VALUES ('Gomitas', null, 6)
INSERT INTO subcategories (name, description, category_id) VALUES ('Agua mineral', null, 2)
INSERT INTO subcategories (name, description, category_id) VALUES ('Agua natural', null, 2)
INSERT INTO subcategories (name, description, category_id) VALUES ('Pan de caja', null, 5)
INSERT INTO subcategories (name, description, category_id) VALUES ('Yogurt', null, 4)
INSERT INTO subcategories (name, description, category_id) VALUES ('Paletas', null, 6)
INSERT INTO subcategories (name, description, category_id) VALUES ('Semillas', null, 7)
INSERT INTO subcategories (name, description, category_id) VALUES ('Vino blanco', null, 8)
INSERT INTO subcategories (name, description, category_id) VALUES ('Jugos', null, 2)
INSERT INTO subcategories (name, description, category_id) VALUES ('Vino rosado', null, 8)
INSERT INTO subcategories (name, description, category_id) VALUES ('Pan dulce', null, 5)
INSERT INTO subcategories (name, description, category_id) VALUES ('Helado base leche', null, 3)
INSERT INTO subcategories (name, description, category_id) VALUES ('Queso', null, 4)
INSERT INTO subcategories (name, description, category_id) VALUES ('Leche', null, 4)
INSERT INTO subcategories (name, description, category_id) VALUES ('Cacahuates', null, 7)
INSERT INTO subcategories (name, description, category_id) VALUES ('Nueces', null, 7)
